services:
  backend:
    build: .
    container_name: messenger_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:17
    container_name: messenger_db
    environment:
      POSTGRES_DB: messenger_db
      POSTGRES_USER: messenger_user
      POSTGRES_PASSWORD: messenger_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: messenger_redis
    ports:
      - "6379:6379"
volumes:
  postgres_data: